# Generated by Django 4.2.3 on 2023-08-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_remove_qna_user_alter_chatroom_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
