# Generated by Django 4.2.3 on 2023-08-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_remove_qna_user_alter_chatroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna',
            name='nexts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna',
            name='question',
            field=models.TextField(),
        ),
    ]
